-- Base de données MySQL pour le projet de recrutement intelligent

CREATE DATABASE IF NOT EXISTS recrutement CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE recrutement;

CREATE TABLE IF NOT EXISTS utilisateur (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  mot_de_passe VARCHAR(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS offre (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titre VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  competences VARCHAR(500) NOT NULL,
  date DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS c_v (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom_fichier VARCHAR(200) NOT NULL,
  texte LONGTEXT NOT NULL,
  score FLOAT DEFAULT 0,
  offre_id INT,
  date DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (offre_id) REFERENCES offre(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
